development:
  adapter: postgresql
  encoding: unicode
  database: echoboard_development
  pool: 5
  username: steno
  password:
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: echoboard_test
  pool: 5
  username: steno
  password:
  host: localhost
  port: 5432
